/**
 * Locating and reading the vendored ODNI packages.
 */
import { mkdirSync, writeFileSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import type { Term } from './emit.ts'
import { CVES_WITHOUT_XSD, type CveGroup } from './manifest.ts'
import { attribute, findAll, readXml } from './xml.ts'

const PACKAGE = join(import.meta.dirname, '..')
/** The vendored packages sit at the repo root. They are not this package's data. */
const ROOT = join(PACKAGE, '..', '..')

export const ISM = join(ROOT, 'references/ISM-Public-Convenience-2022-DEC-Public-Light/ISM')
export const ROLLUP = join(
  ROOT,
  'references/ISM-Rollup-Public-Convenience-2022-DEC-Public-Light/ISM-Rollup',
)
const OUT = join(PACKAGE, 'src/generated')

/** Not a country: stands for Foreign Government Information with a concealed source. */
export const FGI_MARKER = 'FGI'

/** CVE JSON wraps every leaf as `{ text, ism:* }`; some are bare strings. */
const text = (node: unknown): string =>
  typeof node === 'string' ? node : String((node as { text?: unknown })?.text ?? '')

export const cve = (group: CveGroup, name: string): Term[] => {
  const file = join(ISM, 'CVE', group, `${name}.json`)
  const doc = JSON.parse(readFileSync(file, 'utf8')) as {
    CVE?: { Enumeration?: { Term?: unknown } }
  }
  const raw = doc.CVE?.Enumeration?.Term
  const terms = (
    Array.isArray(raw) ? raw : raw === undefined || raw === null ? [] : [raw]
  ) as Array<Record<string, unknown>>

  return terms.map((t) => {
    const term: Term = { value: text(t.Value), description: text(t.Description) }
    const deprecated = t.deprecated
    if (deprecated !== undefined && deprecated !== null) {
      term.deprecated = text(deprecated)
    }
    return term
  })
}

/**
 * Some CVE terms are regular expressions, not literal tokens. Five ISMCAT
 * vocabularies admit `NATO:[a-zA-Z\-_]{1,256}`.
 *
 * The JSON and the CVE XML write a pattern term and a literal term the same way,
 * so neither can tell them apart. The generated XSD can: it holds an `xsd:union`
 * of an `xsd:pattern` restriction and an `xsd:enumeration` restriction. Read the
 * XSD.
 */
export const patternValues = (group: CveGroup, name: string): Set<string> => {
  const xsd = join(ISM, 'CVE/CveSchema', group, 'CVEGenerated', `${name}.xsd`)
  try {
    const patterns = findAll(readXml(xsd), 'pattern')
    return new Set(
      patterns.map((p) => attribute(p, 'value')).filter((v): v is string => v !== undefined),
    )
  } catch (error) {
    throw new Error(`could not arbitrate ${name} patterns from ${xsd}`, { cause: error })
  }
}

/** A CVE's terms with any regular-expression terms separated out. */
export const literalsAndPatterns = (
  group: CveGroup,
  name: string,
): { literals: Term[]; patterns: Term[] } => {
  const key: `${CveGroup}/${string}` = `${group}/${name}`
  const isPattern = CVES_WITHOUT_XSD.has(key) ? new Set<string>() : patternValues(group, name)
  const all = cve(group, name)
  return {
    literals: all.filter((t) => !isPattern.has(t.value)),
    patterns: all.filter((t) => isPattern.has(t.value)),
  }
}

const BANNER = `// Generated by scripts/codegen.ts from the ODNI packages under references/.
// Do not edit by hand — run \`bun run codegen\`.
`

export const write = (file: string, blocks: readonly string[]): void => {
  mkdirSync(OUT, { recursive: true })
  writeFileSync(join(OUT, file), `${BANNER}\n${blocks.join('\n')}`, 'utf8')
  console.log(`  ${file}`)
}
